config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get   '/edit_system_info', to: 'bases#edit_system_info'

  resources :bases

  resources :users do
    collection {post :import} #csvインポート用ルーティング
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'users_at_work'
      get 'attendances/edit_one_day_overtime_application'
      patch 'attendances/update_one_day_overtime_application'
      get 'attendances/edit_overtime_application_notification'
      patch 'attendances/update_overtime_application_notification'
      get 'attendances/overtime_application_confirmation_show'
      get 'attendances/edit_attendance_change_application_notification'
      patch 'attendances/update_attendance_change_application_notification'
      get 'attendances/attendance_change_application_confirmation_show'
      get 'attendances/attendance_modifying_log'
      patch 'attendances/update_affiliation_manager_approval_application'
      get 'attendances/edit_affiliation_manager_approval_application_notification'
      patch 'attendances/update_affiliation_manager_approval_application_notification'
      get 'attendances/affiliation_manager_approval_application_confirmation_show'
      get 'csv_output'
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy

  attr_accessor :remember_token
  before_save { self.email = email.downcase }

  validates :name, presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true
  validates :affiliation, length: { in: 2..30 }, allow_blank: true
  # validates :basic_time, presence: true
  validates :basic_work_time, presence: true
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  def User.digest(string)
    cost =
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end
  
  #importメソッド
  def self.import(file)

    CSV.foreach(file.path, encoding: 'Shift_JIS:UTF-8', headers: true) do |row|
      # IDが見つかれば、レコードを呼び出し、見つかれなければ、新しく作成
      user = find_by(id: row["id"]) || new
      # CSVからデータを取得し、設定する
      user.attributes = row.to_hash.slice(*updatable_attributes)
      user.save
    end
  end
  
  # 更新を許可するカラムを定義
  def self.updatable_attributes
    ["name", "email", "affiliation", "employee_number",  "uid", "password",
     "basic_work_time", "designated_work_start_time", "designated_work_end_time"]
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :csv_output]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info, :show]
  before_action :correct_user, only: [:edit, :update, :show]
  before_action :admin_user, only: [:destroy, :index, :users_at_work, :edit_basic_info, :update_basic_info]
  before_action :set_one_month, only: [:show, :csv_output]

  require 'csv'

  def index
    @users = User.paginate(page: params[:page]).order('id ASC')
  end

  #CSVインポート
  def import
    if params[:file].blank?
      flash[:danger] = "インポートするCSVファイルを選択してください。"
      redirect_to users_url
    elsif
      File.extname(params[:file].original_filename) != ".csv"
      flash[:danger] = "csvファイルのみ読み込み可能です。"
      redirect_to users_url
    else
      User.import(params[:file])
      flash[:success] = "CSVファイルをインポートしました。"
      redirect_to users_url
    end
  end
  
  #csv出力
  def csv_output
    # @attendances = @user.attendances.where()
    @attendances = @user.attendances.where(worked_on: @first_day..@last_day).order(:worked_on)
    
    respond_to do |format|
      format.html
      format.csv do |csv|
        send_users_csv(@attendances)
      end
    end
  end
  
  def send_users_csv(attendances)
    bom = %w(EF BB BF).map { |e| e.hex.chr }.join # bomを作成
    
    csv_data = CSV.generate(bom) do |csv|# generateで引数にbomを渡してあげる
      header = ["日付", "出社時間", "退社時間"]
      csv << header
      @attendances.each do |attendance|
        if attendance.started_at.present? && attendance.finished_at.present? && (attendance.overtime_application_status != "否認" || attendance.attendance_change_application_status != "否認" || attendance.affiliation_manager_approval_application_status != "否認")
          values = [
            l(attendance.worked_on, format: :short),
            l(attendance.started_at, format: :time),
            l(attendance.finished_at, format: :time)
          ]
        elsif attendance.started_at.present? && attendance.finished_at.blank? && (attendance.overtime_application_status != "否認" || attendance.attendance_change_application_status != "否認" || attendance.affiliation_manager_approval_application_status != "否認")
          values = [
            l(attendance.worked_on, format: :short),
            l(attendance.started_at, format: :time),
            attendance.finished_at
          ]
        else
          values = [
            l(attendance.worked_on, format: :short)
            # attendance.started_at,
            # attendance.finished_at
          ]
        end
        csv << values
      end
    end
    send_data(csv_data, filename: "#{@user.name}の#{@first_day.month}月の承認済み勤怠情報.csv")
  end
  
  def show
    if current_user.admin?
      flash[:danger] = '権限がありません'
      redirect_to root_url
    else
      @worked_sum = @attendances.where.not(started_at: nil).count
      
      # respond_to do |format|
      #   format.html
      #   format.csv do |csv|
      #     send_posts_csv(@attendances)
      #   end
      # end
      
      if current_user.superior?
        @target_superior_user_attendances = Attendance.all.where(overtime_application_target_superior_id: params[:id])
        @overtime_application_count = @target_superior_user_attendances.where(overtime_application_status: "申請中").count
        @target_superior_user_for_change_attendances = Attendance.all.where(attendance_change_application_target_superior_id: params[:id])
        @attendance_change_application_count = @target_superior_user_for_change_attendances.where(attendance_change_application_status: "申請中").count
        
        @target_superior_user_for_affiliation_manager_approval_application_attendances = Attendance.all.where(affiliation_manager_approval_application_target_superior_id: params[:id])
        @affiliation_manager_approval_application_count = @target_superior_user_for_affiliation_manager_approval_application_attendances.where(affiliation_manager_approval_application_status: "申請中").count
        @selected_superior_users = User.where(superior: true).where.not(id: @user.id)
        @approval_attendance = @user.attendances.find_by(worked_on: params[:date])
      else
        @target_superior_user_for_affiliation_manager_approval_application_attendances = Attendance.all.where.not(affiliation_manager_approval_application_target_superior_id: nil)
        @affiliation_manager_approval_application_count = @target_superior_user_for_affiliation_manager_approval_application_attendances.where(affiliation_manager_approval_application_status: "申請中").count
        @selected_superior_users = User.where(superior: true)
        @approval_attendance = @user.attendances.find_by(worked_on: params[:date])
      end
    end
  end

  def new
    @user = User.new # ユーザーオブジェクトを生成し、インスタンス変数に代入します。
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      render :edit
      # redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end

  def update_basic_info #_user.html.erbからここへ飛ぶ　更新しフラッシュ表示　一覧に戻る
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end

  def users_at_work
    @users = User.all.includes(:attendances)
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :affiliation, :password, :password_confirmation)
    end

    def basic_info_params
      params.require(:user).permit(:name, :email, :affiliation, :employee_number, :uid, :basic_work_time,
                                    :designated_work_start_time, :designated_work_end_time)
    end
    
    # def send_posts_csv(attendances)
    #   csv_data = CSV.generate do |csv|
    #     column_names = %w(日付　出社時間　退社時間)
    #     csv << column_names
    #     attendances.each do |day|
    #       column_values = [
    #         day.worked_on,
    #         day.started_at,
    #         day.finished_at,
    #       ]
    #       csv << column_values
    #     end
    #   end
    #   send_data(csv_data, filename: "承認済み勤怠情報.csv")
    # end

end

app/helpers/users_helper.rb
module UsersHelper
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/_user.html.erb
<%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
<!--update_basic_infoに飛ばして更新及びフラッシュを表示し、一覧に戻る-->
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :affiliation, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :affiliation, class: "form-control" %>

  <%= f.label :employee_number, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :employee_number, class: "form-control" %>
  
  <%= f.label :uid, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :uid, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <!--< %= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>-->
  <!--< %= f.password_field :password_confirmation, class: "form-control" %>-->
  
  <%= f.label :basic_work_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :basic_work_time, class: "form-control" %>
  
  <%= f.label :designated_work_start_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_start_time, class: "form-control" %>

  <%= f.label :designated_work_end_time, class: "label-#{yield(:class_text)}" %>
  <%= f.time_field :designated_work_end_time, class: "form-control" %>

  <div class="center">
    <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>ユーザー登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "⇦", user_path(date: @first_day.prev_month), class: "btn btn-primary" %>
        【<%= l(@first_day, format: :middle) %>】勤怠管理表
        <%= link_to "⇨", user_path(date: @first_day.next_month), class: "btn btn-primary" %>
      </td>
      <td>
        指定勤務開始時間　<%= @user.designated_work_start_time.present? ? l(@user.designated_work_start_time, format: :time) : "未設定" %><br>
        指定勤務終了時間　<%= @user.designated_work_end_time.present? ? l(@user.designated_work_end_time, format: :time) : "未設定" %>
      </td>
      <td colspan="3">基本時間　<%= format_basic_info(@user.basic_time) %></td>
      <td>初日　<%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属　<%= @user.affiliation.present? ? @user.affiliation : "未所属" %></td>
      <td>名前　<%= @user.name %></td>
      <td>コード</td>
      <td><%= @user.uid %></td>
      <td>出勤日数　<%= @worked_sum %>日</td>
      <td>締め　<%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<ul class = "infomation">
  <% if current_user.superior? %>
    <li>
      <% if @affiliation_manager_approval_application_count >= 1 %>
        <p class = "notification">
        <%= link_to "【所属長承認申請のお知らせ】",
        attendances_edit_affiliation_manager_approval_application_notification_user_path, remote: true
        %>
        <a class = "box1"><%= @affiliation_manager_approval_application_count %>件の通知があります</a>
        </p>
      <% else %>
        <p>【所属長承認申請のお知らせ】</p>
      <% end %>
    </li>
    <li>
      <% if @attendance_change_application_count >= 1 %>
        <p class = "notification">
          <%= link_to "【勤怠変更申請のお知らせ】",
          attendances_edit_attendance_change_application_notification_user_path, remote: true
          %>
          <a class = "box1"><%= @attendance_change_application_count %>件の通知があります</a>
        </p>
      <% else %>
        <p>【勤怠変更申請のお知らせ】</p>
      <% end %>
    </li>
    <li>
      <% if @overtime_application_count >= 1 %>
        <p class = "notification">
          <%= link_to "【残業申請のお知らせ】",
          attendances_edit_overtime_application_notification_user_path, remote: true
          %>
          <a class = "box1"><%= @overtime_application_count %>件の通知があります</a>
        </p>
      <% else %>
        <p>【残業申請のお知らせ】</p>
      <% end %>
    </li>
  <% end %>
</ul>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
  <!--< %= link_to "CSV出力", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %><br>-->
  <%= link_to "CSV出力", csv_output_user_path(date: @first_day, format: :csv), class: "btn btn-primary" %><br>
  <%= link_to "勤怠修正ログ（承認済）", attendances_attendance_modifying_log_user_path(date: @first_day), class: "btn btn-primary" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-striped table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="3">残業申請</th>
        <th rowspan="3">日付</th>
        <th rowspan="3">曜日</th>
        <th colspan="8">【実績】</th>
        <th colspan="5">所定外勤務</th>
      </tr>
      <tr>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
        <th colspan="2">終了予定時間</th>
        <th rowspan="2">時間外時間</th>
        <th rowspan="2">業務処理内容</th>
        <th rowspan="2">指示者確認㊞</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <tr>
          <td>
            <%= link_to "残業申請",
            attendances_edit_one_day_overtime_application_user_path(@user, date: day.worked_on),
            remote: true, class: "btn btn-primary" 
            %>
          </td>
          <% css_class =
            case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
            when '土'
              'text-primary'
            when '日'
              'text-danger'
            end
          %>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= %w{日 月 火 水 木 金 土}[day.worked_on.wday] %></td>
          <!--<td>< %= format_hour(day.started_at) if day.started_at.present? && (day.attendance_change_application_status == "承認" || day.attendance_change_application_status == "" || day.attendance_change_application_status == nil) %></td>-->
          <!--<td>< %= format_min(day.started_at) if day.started_at.present? && (day.attendance_change_application_status == "承認" || day.attendance_change_application_status == "" || day.attendance_change_application_status == nil) %></td>-->
          <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) && !day.started_at.present? %>
              <%= link_to "出社", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <!--<td>< %= format_hour(day.finished_at) if day.finished_at.present? && (day.attendance_change_application_status == "承認" || day.attendance_change_application_status == "" || day.attendance_change_application_status == nil) %></td>-->
          <!--<td>< %= format_min(day.finished_at) if day.finished_at.present? && (day.attendance_change_application_status == "承認" || day.attendance_change_application_status == "" || day.attendance_change_application_status == nil) %></td>-->
          <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) && day.started_at.present? %>
              <%= link_to "退社", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td>
            <!--< % if day.started_at.present? && day.finished_at.present? && (day.attendance_change_application_status == "承認" || day.attendance_change_application_status == "" || day.attendance_change_application_status == nil) %>-->
            <% if day.started_at.present? && day.finished_at.present? %>
              <%= str_times = working_times(day.started_at, day.finished_at, day.next_day) %>
              <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
          <td><%= format_hour(day.scheduled_end_time) if (day.scheduled_end_time.present? && day.overtime_application_status == "承認") %></td>
          <td><%= format_min(day.scheduled_end_time) if day.scheduled_end_time.present? && day.overtime_application_status == "承認" %></td>
          <td>
            <% if day.scheduled_end_time.present? && day.overtime_application_status == "承認" %>
              <%= overtime(@user.designated_work_end_time, day.next_day, day.scheduled_end_time, day.worked_on) %>
            <% end %>
          </td>
          <td><%= day.business_process_content %></td>
          <td>
            <% if day.overtime_application_status.present? %>
              <% if day.overtime_application_status == "申請中" %>
                <%= "#{User.find(day.overtime_application_target_superior_id).name}に残業#{day.overtime_application_status}" %>
              <% elsif day.overtime_application_status == "承認" %>
                <%= "残業#{day.overtime_application_status}済" %>
              <% else day.overtime_application_status == "否認" %>
                <%= "残業#{day.overtime_application_status}" %>
              <% end %>
            <% end %>
            
            <% if day.overtime_application_status.present? %>
              <br>
            <% end %>
            
            <% if day.attendance_change_application_status.present? %>
              <% if day.attendance_change_application_status == "申請中" %>
                <%= "#{User.find(day.attendance_change_application_target_superior_id).name}に勤怠変更#{day.attendance_change_application_status}" %>
              <% elsif day.attendance_change_application_status == "承認" %>
                <%= "勤怠変更#{day.attendance_change_application_status}済" %>
              <% else day.attendance_change_application_status == "否認" %>
                <%= "勤怠変更#{day.attendance_change_application_status}" %>
              <% end %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

    <tfoot>
      <tr>
        <td rowspan="2"></td>
        <td colspan="2">累計日数</td>
        <td colspan="6">総合勤務時間</td>
        <td>累計在社時間</td>
        <td colspan="5", rowspan="2"></td>
        <td rowspan="2">
          <% if Attendance.find_by(worked_on: @first_day, user_id: params[:id], affiliation_manager_approval_application_status: "申請中").present? %>
            <p>
              <%= User.find_by(id: Attendance.find_by(worked_on: @first_day, user_id: params[:id], affiliation_manager_approval_application_status: "申請中").affiliation_manager_approval_application_target_superior_id).name %>
              に所属長承認申請中
            </p>
          <% elsif Attendance.find_by(worked_on: @first_day, user_id: params[:id], affiliation_manager_approval_application_status: "承認").present? %>
            <p>
              所属長承認　<%= User.find_by(id: Attendance.find_by(worked_on: @first_day, user_id: params[:id], affiliation_manager_approval_application_status: "承認").affiliation_manager_approval_application_target_superior_id).name %>
              から承認済
            </p>
          <% elsif Attendance.find_by(worked_on: @first_day, user_id: params[:id], affiliation_manager_approval_application_status: "否認").present? %>
            <p>
              所属長承認　<%= User.find_by(id: Attendance.find_by(worked_on: @first_day, user_id: params[:id], affiliation_manager_approval_application_status: "否認").affiliation_manager_approval_application_target_superior_id).name %>
              から否認
            </p>
          <% else %>
            <p>所属長承認　未</p>
          <% end %>
            <%= form_with(model: @approval_attendance, url: attendances_update_affiliation_manager_approval_application_user_path(date: @first_day), local: true, method: :patch) do |f| %>
              <%= f.collection_select(:affiliation_manager_approval_application_target_superior_id, @selected_superior_users, :id, :name, {prompt: ""}) %>
              <%= f.hidden_field :affiliation_manager_approval_application_status, :value => "申請中"  %>
              <%= f.hidden_field :worked_on, :value => @first_day  %>
              <div class="center">
                <%= f.submit "申請", class: "btn btn-primary" %>
              </div>
            <% end %>
        </td>
      </tr>
      <tr>
        <td colspan="2"><%= @attendances.count %></td>
        <td colspan="6"><%= format_basic_info(@user.basic_work_time).to_f * @worked_sum %></td>
        <td><%= format("%.2f", @total_working_times.to_f) %></td>
        <!--<td colspan="5"></td>-->
      </tr>
    </tfoot>
  </table>
</div>

<!--モーダルウインドウ表示-->
<!--1日分の残業申請-->
<div id="edit_one_day_overtime_application" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--残業申請のおしらせ-->
<div id="edit_overtime_application_notification" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--勤怠変更申請のおしらせ-->
<div id="edit_attendance_change_application_notification" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
<!--所属長承認申請のおしらせ-->
<div id="edit_affiliation_manager_approval_application_notification" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>

app/views/users/users_at_work.html.erb
<% provide(:title, 'Users at work') %>
<h1>出勤中社員一覧</h1>

<div class="col-md-10 col-md-offset-1">
  <table class="table table-bordered table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <td>社員番号</br>
        <td>名前</td>
      </tr>
    </thead>
    <% @users.each do |user| %>
      <tr>
        <% user.attendances.each do |day| %>
          <% if day.started_at.present? && day.finished_at.nil? %>
            <td><%= user.employee_number %></td>
            <td><%= user.name %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </table>
</div>