config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#top'
  get '/signup', to: 'users#new'

  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get   '/edit_system_info', to: 'bases#edit_system_info'

  resources :bases

  resources :users do
    collection {post :import} #csvインポート用ルーティング
    member do
      get 'edit_basic_info'
      patch 'update_basic_info'
      get 'attendances/edit_one_month'
      patch 'attendances/update_one_month'
      get 'users_at_work'
      get 'attendances/edit_one_day_overtime_application'
      patch 'attendances/update_one_day_overtime_application'
      get 'attendances/edit_overtime_application_notification'
      patch 'attendances/update_overtime_application_notification'
      get 'attendances/overtime_application_confirmation_show'
      get 'attendances/edit_attendance_change_application_notification'
      patch 'attendances/update_attendance_change_application_notification'
      get 'attendances/attendance_change_application_confirmation_show'
      get 'attendances/attendance_modifying_log'
      patch 'attendances/update_affiliation_manager_approval_application'
      get 'attendances/edit_affiliation_manager_approval_application_notification'
      patch 'attendances/update_affiliation_manager_approval_application_notification'
      get 'attendances/affiliation_manager_approval_application_confirmation_show'
      get 'csv_output'
    end
    resources :attendances, only: :update
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "勤怠システム", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "トップへ", root_path %></li>
        <% if logged_in? %>
          <% if current_user.admin? %>
            <li><%= link_to "ユーザー一覧", users_path %></li>
            <li><%= link_to "出勤中社員一覧", users_at_work_user_path(current_user) %></li>
            <li><%= link_to "拠点情報の修正", bases_path %></li>
            <li><%= link_to "基本情報の修正", edit_system_info_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% unless current_user.admin? %>
                <li><%= link_to "勤怠", current_user %></li>
              <% end %>
              <li><%= link_to "設定", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg.html_safe %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>